name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@ec2-18-207-115-218.compute-1.amazonaws.com << 'EOF'
            cd ~/app || git clone git@github.com:sohamAspire/DemoNode.git app && cd app
            git pull origin master
            npm install
            pm2 restart server.js || pm2 start server.js --name node-app
            pm2 save
          EOF
