name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-54-175-209-139.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      
      - name: Debug SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -lah ~/.ssh
          cat ~/.ssh/id_rsa | head -n 5  # Show first few lines of key for debugging

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa ubuntu@54.175.209.139 "echo SSH Connected Successfully!"

      - name: Deploy Code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@54.175.209.139 << 'EOF'
            cd /home/ubuntu/app
            git pull origin master
            npm install
            pm2 restart all  # Restart Node.js server
          EOF
